### 회원가입 OK
POST http://localhost:8080/api/v1/members

### 로그인 OK
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "password1234!@"
}

### 토큰 재발급 OK
POST http://localhost:8080/api/v1/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMWVkYWQzOS0yZDJhLTIwY2YtODQ3OS0yIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjc2NDcwMjY1fQ.s-tpU_MfYU5k77xHGaIvn_5FLX_PjUHk7KGYpxDdlcRS79KkZGOWAUWDRbbcpXPMdC9xQK-Tus0h5viAvjMLwQ
Cookie: Refresh=Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMWVkYWQzOS0yZDJhLTIwY2YtODQ3OS0yIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjc3MDc0NDY1fQ.1uxuV2-8lJQ6nff4RXRJ7xvRsb7X8Cb6r3dU_ohXOOrFlC2o7xLC1f_h5eBGMf0DIxknlJArFKdKyduKZYgxCA; Path=/; Max-Age=604799097; Expires=Wed, 16 Apr 2042 13:46:03 GMT; HttpOnly; SameSite=None

### 로그 아웃 OK
POST http://localhost:8080/api/v1/log-out
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMWVkYWQzOS0yZDJhLTIwY2YtODQ3OS0yIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjc2NDcwMjY1fQ.s-tpU_MfYU5k77xHGaIvn_5FLX_PjUHk7KGYpxDdlcRS79KkZGOWAUWDRbbcpXPMdC9xQK-Tus0h5viAvjMLwQ

### 게시판 생성 OK
POST http://localhost:8080/api/v1/board
Content-Type:multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMWVkYWQzOS0yZDJhLTIwY2YtODQ3OS0yIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjc2NDcwMjY1fQ.s-tpU_MfYU5k77xHGaIvn_5FLX_PjUHk7KGYpxDdlcRS79KkZGOWAUWDRbbcpXPMdC9xQK-Tus0h5viAvjMLwQ

--boundary
Content-Disposition:  form-data; name="form"
Content-Type: application/json


{
    "title":"자바 질문 드립니당",
    "context":"동시성 문제를 ThreadLocal, Atomic 객체, synchronized를 사용해서 해결하는 예제가 있을까요? ",
    "category":"QUESTION",
    "topic": "JAVA"
}

### 게시판 리스트 조회 OK
GET http://localhost:8080/api/v1/board

### 게시판 상세 조회 OK
GET http://localhost:8080/api/v1/board/1

### 게시판 수정 OK
PATCH http://localhost:8080/api/v1/board/1
Content-Type:multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMWVkYWQzMy04ZjMzLTE0MmUtOWZhOC0yIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjc2NDY3ODYzfQ.dQmUakpsJ8pOBg_LEuBbWKfvRgYpWvTB1myjHYCzVfd9F7kKC1TicGGCpQb185uM8y-YGhLQqgxEa3ntnuNHtQ

--boundary
Content-Disposition:  form-data; name="form"
Content-Type: application/json

{
    "title":"수정된 제목",
    "contents":"수정된 내용",
    "category":"KNOWLEDGE",
    "topic": "MYSQL"
}

### 댓글 생성 OK
POST http://localhost:8080/api/v1/board/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMWVkYWQzMy04ZjMzLTE0MmUtOWZhOC0yIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjc2NDY3ODYzfQ.dQmUakpsJ8pOBg_LEuBbWKfvRgYpWvTB1myjHYCzVfd9F7kKC1TicGGCpQb185uM8y-YGhLQqgxEa3ntnuNHtQ

{
  "text" : "댓글달린다"
}

### 댓글 조회
GET http://localhost:8080/api/v1/board/1/comments

### 댓글 수정

### 댓글 삭제

### 대댓글 생성

### 대댓글 수정

### 대댓글 삭제

