### 로그인
POST https://www.bad-request.kr/api/v1/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "password1234!@"
}

### 게시판 목록
GET https://www.bad-request.kr/api/v1/board?size=3&category=COMMUNITY
Content-Type: application/json

