server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2/console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  logging:
    level:
      org.hibernate.SQL:
        type.descriptor.sql: trace
        SQL: DEBUG

logging:
  level:
    root: info
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.data.*.*: DEBUG
    org.springframework.cache.*: DEBUG

message:
  hello: This is dev server

token:
  secret-key: thisIsVeryVeryVeryImportantSecretKeySoMustHideThisKey
  access-life: 3
  refresh-life: 4
#개발환경에서는 HTTPS 적용 x
cookie-status:
  secure: false
