server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/BAD_REQUEST?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 0209

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        show_sql: true
    open-in-view: false
    database: mysql

logging:

  pattern:
#    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    file: "[%d{yyyy-MM-dd-HH:mm}][%-5level][%thread][%logger] - %msg%n"
  file:
    name: /Users/leechoongsub/desktop/log/test.log
  level:
    root: INFO
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
#    org.springframework.data.*.*: DEBUG
#    org.springframework.cache.*: DEBUG
  logback:
    rolling policy:
      file-name-pattern: "/Users/leechoongsub/desktop/log/test.log.%d{yyyy-MM-dd}.%i"
      max-file-size: 5MB

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


message:
  hello: This is test server

token:
  secret-key: thisIsVeryVeryVeryImportantSecretKeySoMustHideThisKey
  access-life: 600
  refresh-life: 604800

cookie-status:
  secure: false