
### 로그인
POST http://localhost:8080/api/v2/login
Content-Type: application/json

{
  "email": "sample@gmail.com",
  "password": "sample1234!@"
}

> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.global.set("refresh_token", response.headers.valueOf("Set-Cookie").split(";")[0]);

    client.log(client.global.get("access_token"));
    client.log(client.global.get("refresh_token"));
%}

### 질문 게시판 리스트 조회
GET http://localhost:8080/api/v2/questions?size=3

### 질문 게시판 리스트 조회 + 정렬 view
GET http://localhost:8080/api/v2/questions?size=5&sort=view

### 질문 게시판 리스트 조회 + 정렬 recommend
GET http://localhost:8080/api/v2/questions?size=5&sort=recommend

### 질문 상세 보기
GET http://localhost:8080/api/v2/questions/50

### 질문 답변 목록
GET http://localhost:8080/api/v2/questions/3/answers

### 질문 등록
POST http://localhost:8080/api/v2/questions
Content-Type: application/json
Authorization: {{access_token}}

{
  "title": "제목",
  "contents": "내용 입니다.!!",
  "tags": [
    "tag1",
    "tag2"
  ]
}

### 질문 수정
PATCH http://localhost:8080/api/v2/questions/10
Content-Type: application/json
Authorization: {{access_token}}

{
  "title": "수정 제목",
  "contents": "수정된 제목"
}

### 질문 추천
POST http://localhost:8080/api/v2/questions/20/recommendations?recommend=true

### 질문 추천 취소
DELETE http://localhost:8080/api/v2/questions/10/recommendations

