### 회원가입 OK
POST http://localhost:8080/api/v1/members

### 로그인 OK
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "user@gmail.com50",
  "password": "password1234!@"
}

> {%
client.global.set("access_token", response.headers.valueOf("Authorization"));
client.global.set("refresh_token", response.headers.valueOf("Set-Cookie").split(";")[0]);

client.log(client.global.get("access_token"));
client.log(client.global.get("refresh_token"));
%}

### 토큰 재발급 OK
POST http://localhost:8080/api/v1/refresh
Content-Type: application/json
Authorization: {{access_token}}
Cookie: {{refresh_token}}

### 로그 아웃 OK
POST http://localhost:8080/api/v1/log-out
Authorization: {{access_token}}

### 게시판 생성 OK
POST http://localhost:8080/api/v1/board
Content-Type:multipart/form-data; boundary=boundary
Authorization: {{access_token}}

--boundary
Content-Disposition:  form-data; name="form"
Content-Type: application/json


{
    "title":"자바 질문 드립니당",
    "contents":"동시성 문제를 ThreadLocal, Atomic 객체, synchronized를 사용해서 해결하는 예제가 있을까요? ",
    "category":"QUESTION",
    "topic": "JAVA"
}

### 게시판 리스트 조회 OK
GET http://localhost:8080/api/v1/board?size=20



### 게시판 상세 조회 OK
GET http://localhost:8080/api/v1/board/1

### 게시판 수정 OK
PATCH http://localhost:8080/api/v1/board/1
Content-Type:multipart/form-data; boundary=boundary
Authorization: {{access_token}}

--boundary
Content-Disposition:  form-data; name="form"
Content-Type: application/json

{
    "title":"수정된 제목",
    "contents":"수정된 내용",
    "category":"KNOWLEDGE",
    "topic": "MYSQL"
}

### 댓글 생성 OK
POST http://localhost:8080/api/v1/board/1/comments
Content-Type: application/json
Authorization: {{access_token}}

{
  "text": "댓글달린다"
}

### 댓글 조회
GET http://localhost:8080/api/v1/board/1/comments?size=3
Content-Type: application/json

### 댓글 수정
PUT http://localhost:8080/api/v1/board/1/comments/1
Content-Type: application/json
Authorization: {{access_token}}

{
  "text" : "수정된 댓글"
}
### 댓글 삭제
DELETE http://localhost:8080/api/v1/board/1/comments/1
Content-Type: application/json
Authorization: {{access_token}}

### 대댓글 조회
GET http://localhost:8080/api/v1/comments/1/sub-comments
Content-Type: application/json

### 대댓글 생성
POST http://localhost:8080/api/v1/comments/1/sub-comments
Content-Type: application/json
Authorization: {{access_token}}

{
  "text" : "대댓글"
}

### 대댓글 수정
PUT http://localhost:8080/api/v1/comments/1/sub-comments/1
Content-Type: application/json
Authorization: {{access_token}}

{
  "test" : "대댓글 수정"
}

### 대댓글 삭제
DELETE http://localhost:8080/api/v1/comments/1/sub-comments/1
Content-Type: application/json
Authorization: {{access_token}}

### 로그 추적
GET localhost:8080/api/v1/dashboard/log