### 이메일 인증 코드 요청
POST http://localhost:8080/api/v2/members/email-authentication
Content-Type: application/json

{
  "email": "cszzang89@gmail.com"
}

### 회원가입
POST http://localhost:8080/api/v2/members
Content-Type: application/json

{
  "email": "cszzang89@gmail.com",
  "password": "member1!@#",
  "nickname": "nickname",
  "contact": "010-1214-234543",
  "authenticationCode": "417234"
}

### 메일 인증
PATCH http://localhost:8080/api/v2/members/1/email?authenticationCode=445773

### 임시비밀번호 발급
POST http://localhost:8080/api/v2/members/temporary-password
Content-Type: application/json

{
  "email": "cszzang89@gmail.com"
}

### 로그인
POST http://localhost:8080/api/v2/login
Content-Type: application/json

{
  "email": "sample@gmail.com",
  "password": "sample1234!@"
}

> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.global.set("refresh_token", response.headers.valueOf("Set-Cookie").split(";")[0]);

    client.log(client.global.get("access_token"));
    client.log(client.global.get("refresh_token"));
%}

### 토큰 재발급 OK
POST http://localhost:8080/api/v2/refresh
Content-Type: application/json
Authorization: {{access_token}}
Cookie: {{refresh_token}}

### 계정 정보 조회
GET http://localhost:8080/api/v2/members/1
Authorization: {{access_token}}
Cookie: {{refresh_token}}

### 프로필 정보 조회
GET http://localhost:8080/api/v2/members/1/profile


### 비밀번호 변경
PATCH http://localhost:8080/api/v2/members/1/password
Content-Type: application/json
Authorization: {{access_token}}

{
  "currentPassword": "member1!@#",
  "newPassword": "newPassword1234!@"
}

### 로그인한 회원 정보
GET http://localhost:8080/api/v2/members/1/loggedInMember
Content-Type: application/json
Authorization: {{access_token}}

### 인증 코드로 로그인
POST http://localhost:8080/api/v2/login/authentication-code
Content-Type: application/json

{
  "code": "1f1e87c8-29a8-4147-8439-14f15dc9a548"
}

### 로그아웃
POST http://localhost:8080/api/v2/logout
Authorization: {{access_token}}
Cookie: {{refresh_token}}

